apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-cloud
spec:
  replicas: 3
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: demo-cloud
  template:
    metadata:
      labels:
        app: demo-cloud
    spec:
      containers:
      - image: index.docker.io/ciberkleid/java-maven-sample-app:latest
        name: demo-cloud
        ports:
        - containerPort: 8080
